# Generated by Django 3.2.16 on 2024-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, help_text='Optional field', max_length=20, verbose_name='Surname')),
                ('birthday', models.DateField(verbose_name='Birthday')),
            ],
        ),
    ]
